export const MOVE_PACMAN_LEFT = 'MOVE_PACMAN_LEFT';
export type MOVE_PACMAN_LEFT = typeof MOVE_PACMAN_LEFT;

export const MOVE_PACMAN_RIGHT = 'MOVE_PACMAN_RIGHT';
export type MOVE_PACMAN_RIGHT = typeof MOVE_PACMAN_RIGHT;

export const MOVE_PACMAN_UP = 'MOVE_PACMAN_UP';
export type MOVE_PACMAN_UP = typeof MOVE_PACMAN_UP;

export const MOVE_PACMAN_DOWN = 'MOVE_PACMAN_DOWN';
export type MOVE_PACMAN_DOWN = typeof MOVE_PACMAN_DOWN;

export const MOVE_GHOST_LEFT = 'MOVE_GHOST_LEFT';
export type MOVE_GHOST_LEFT = typeof MOVE_GHOST_LEFT;

export const MOVE_GHOST_RIGHT = 'MOVE_GHOST_RIGHT';
export type MOVE_GHOST_RIGHT = typeof MOVE_GHOST_RIGHT;

export const MOVE_GHOST_UP = 'MOVE_GHOST_UP';
export type MOVE_GHOST_UP = typeof MOVE_GHOST_UP;

export const MOVE_GHOST_DOWN = 'MOVE_GHOST_DOWN';
export type MOVE_GHOST_DOWN = typeof MOVE_GHOST_DOWN;

export const SET_TARGET = 'SET_TARGET';
export type SET_TARGET = typeof SET_TARGET;

export const SET_TARGET_KEYBOARD = 'SET_TARGET_KEYBOARD';
export type SET_TARGET_KEYBOARD = typeof SET_TARGET_KEYBOARD;
